# Generated by Django 2.2.4 on 2019-08-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='receive_email',
            field=models.BooleanField(default=False),
        ),
    ]
