# Generated by Django 2.2.4 on 2019-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_profile_receive_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cpf',
            field=models.CharField(default=None, max_length=11, null=True),
        ),
    ]
